from __future__ import annotations

import unittest
from pathlib import Path


STATIC_DIR = Path(__file__).resolve().parents[1] / "my_agent" / "web" / "static"


class WebStaticUITests(unittest.TestCase):
    def test_static_ui_exposes_design_surface(self) -> None:
        html = (STATIC_DIR / "index.html").read_text(encoding="utf-8")
        css = (STATIC_DIR / "style.css").read_text(encoding="utf-8")
        js = (STATIC_DIR / "app.js").read_text(encoding="utf-8")

        self.assertIn('id="topicSource"', html)
        self.assertIn('id="refineTopic" type="button" class="primary"', html)
        self.assertIn('class="app-header"', html)
        self.assertIn('class="app-body"', html)
        self.assertIn('id="newDiscussion"', html)
        self.assertIn('id="startDiscussion"', html)
        self.assertIn('id="conversationEmpty"', html)
        self.assertIn('id="topicEditor" class="topic-editor hidden"', html)
        self.assertIn('id="sessionTopicSummary" class="session-topic-summary hidden"', html)
        self.assertIn('id="messageForm" class="message-form hidden"', html)
        self.assertIn('id="messageStatus"', html)
        self.assertIn('id="sendMessage"', html)
        self.assertIn('id="controlPane"', html)
        self.assertIn('id="sessionPersonaShell"', html)
        self.assertIn('id="sessionPersonaTabs"', html)
        self.assertIn('id="sessionPersonaListTab"', html)
        self.assertIn('id="sessionPersonaEditorTab"', html)
        self.assertIn('id="sessionPersonaBody"', html)
        self.assertIn('id="sessionPersonaEditor"', html)
        self.assertIn('id="sessionPersonaName"', html)
        self.assertIn('id="sessionProviderSelect"', html)
        self.assertIn('id="sessionModelSelect"', html)
        self.assertIn('id="sessionPersonaPrompt"', html)
        self.assertIn('id="saveSessionPersona"', html)
        self.assertIn('id="closeSessionPersonaEditor"', html)
        self.assertIn('id="toggleTopicCard"', html)
        self.assertIn('class="topic-card-detail"', html)
        self.assertIn('id="openSettings"', html)
        self.assertIn('id="settingsDrawer"', html)
        self.assertNotIn('id="personaSettingsList"', html)
        self.assertIn('id="discussionPersonaList"', html)
        self.assertIn('id="sessionAddPersona"', html)
        self.assertIn('id="sessionPersonaList"', html)
        self.assertIn('id="settingsMenu"', html)
        self.assertIn('id="providerSettingsPanel"', html)
        self.assertIn('id="personaManagePanel"', html)
        self.assertIn('id="configSettingsPanel"', html)
        self.assertIn('class="persona-manage-layout"', html)
        self.assertIn('id="providerForm"', html)
        self.assertIn('class="provider-list-panel"', html)
        self.assertIn('id="providerList"', html)
        self.assertIn('id="providerListSummary"', html)
        self.assertNotIn('id="testProviderSelect"', html)
        self.assertNotIn('id="testModelSelect"', html)
        self.assertNotIn('id="testProvider"', html)
        self.assertIn('id="providerTestStatus"', html)
        self.assertIn('id="providerId"', html)
        self.assertIn('id="providerModels"', html)
        self.assertIn('id="addProvider"', html)
        self.assertIn('id="cancelProviderEdit"', html)
        self.assertIn('id="newPersona"', html)
        self.assertIn('添加 LLM Provider', html)
        self.assertIn('新增角色', html)
        self.assertIn('删除角色', html)
        self.assertIn('data-settings-tab="providers"', html)
        self.assertIn('data-settings-tab="personas"', html)
        self.assertIn('data-settings-tab="config"', html)
        self.assertIn('🎭 爆梗圆桌', html)
        self.assertIn('让不同角色把严肃话题聊得有梗', html)
        self.assertIn('围绕本场主题继续补充观点、追问或抛个梗...', html)
        self.assertIn('📜 话题历史', html)
        self.assertIn('🎭 本场嘉宾', html)
        self.assertIn("--bg: #0F172A", css)
        self.assertIn("--accent: #3B82F6", css)
        self.assertIn("status-chip", css)
        self.assertIn("persona-dot", css)
        self.assertIn("role-card", css)
        self.assertIn("message-bubble", css)
        self.assertIn("history-footer", css)
        self.assertIn("conversation-empty", css)
        self.assertIn(".topic-card.is-compact", css)
        self.assertIn("session-topic-summary", css)
        self.assertIn("session-persona-shell", css)
        self.assertIn("session-persona-body", css)
        self.assertIn("session-persona-tabs", css)
        self.assertIn("session-persona-tab", css)
        self.assertIn("session-persona-tab.is-active", css)
        self.assertIn("session-persona-editor", css)
        self.assertIn("--header-height: 64px", css)
        self.assertIn("top: var(--header-height)", css)
        self.assertIn("width: min(520px, calc(100vw - 24px))", css)
        self.assertIn("position: fixed", css)
        self.assertIn("scrollbar-gutter: stable", css)
        self.assertIn("grid-template-columns: 12px minmax(0, 1fr)", css)
        self.assertIn("min-height: 64px", css)
        self.assertIn(".persona-item.role-card > .persona-dot", css)
        self.assertIn("height: 40px", css)
        self.assertIn("border-bottom-color: var(--accent)", css)
        self.assertIn("scrollbar-width: thin", css)
        self.assertIn("message-status", css)
        self.assertIn("settings-drawer", css)
        self.assertIn("width: min(1120px, calc(100vw - 48px))", css)
        self.assertIn("left: 50%", css)
        self.assertIn("transform: translateX(-50%)", css)
        self.assertIn("settings-menu", css)
        self.assertIn("settings-panel", css)
        self.assertIn("persona-manage-layout", css)
        self.assertIn("grid-template-columns: minmax(240px, 300px) minmax(0, 1fr)", css)
        self.assertIn("discussion-persona-picker", css)
        self.assertIn("session-persona-picker", css)
        self.assertIn("persona-status-card", css)
        self.assertIn(".persona-item.tone-blue", css)
        self.assertIn("grid-template-columns: 300px minmax(0, 1fr) 360px", css)
        self.assertIn("width: 550px", css)
        self.assertIn("max-width: calc(100% - 52px)", css)
        self.assertIn("overflow-wrap: anywhere", css)
        self.assertIn("width: 40px", css)
        self.assertIn("border-radius: 16px", css)
        self.assertIn("sourceLabels", js)
        self.assertIn("clarification-answer", js)
        self.assertIn("renderTopicTags", js)
        self.assertIn("renderWorkSurface", js)
        self.assertIn("startDiscussion", js)
        self.assertIn("toggleTopicCard", js)
        self.assertIn("openSettings", js)
        self.assertIn("closeSettings", js)
        self.assertIn("switchSettingsTab", js)
        self.assertIn("renderDiscussionPersonaList", js)
        self.assertIn("addSessionPersonas", js)
        self.assertIn("addProvider", js)
        self.assertIn("renderProviderList", js)
        self.assertIn("provider-row", js)
        self.assertIn("editingProviderId", js)
        self.assertIn("editProvider", js)
        self.assertIn("deleteProvider", js)
        self.assertIn("cancelProviderEdit", js)
        self.assertIn("provider-actions", js)
        self.assertIn("provider-edit-button", js)
        self.assertIn("provider-delete-button", js)
        self.assertIn("testProviderConnection", js)
        self.assertIn("personaModelDirty", js)
        self.assertIn("syncPersonaModelPicker", js)
        self.assertIn("displayPersonaModel", js)
        self.assertIn("systemPersonaForSessionPersona", js)
        self.assertIn("sessionPersonaView", js)
        self.assertIn("switchSessionPersonaView", js)
        self.assertIn("closeSessionPersonaEditor", js)
        self.assertIn("renderSessionPersonaEditor", js)
        self.assertIn("saveSessionPersona", js)
        self.assertNotIn("点击微调", js)
        self.assertNotIn("persona-card-hint", js)
        self.assertNotIn("sourcePersona?.display_name", js)
        self.assertIn('if (!state.currentSession?.personas?.length) return [];', js)
        self.assertIn('state.sessionPersonaView = "editor"', js)
        self.assertIn('state.sessionPersonaView = "list"', js)
        self.assertIn('$("sessionPersonaEditorTab").disabled', js)
        self.assertIn('body.classList.toggle("editor-open"', js)
        self.assertIn("/api/sessions/${state.currentSession.id}/personas/${persona.persona_id}", js)
        self.assertIn('payload.provider_id = $("providerSelect").value', js)
        self.assertIn('payload.model = $("modelSelect").value', js)
        self.assertIn("/api/providers/test", js)
        self.assertIn("provider-list-panel", css)
        self.assertIn("provider-row", css)
        self.assertIn("provider-actions", css)
        self.assertIn("provider-test-status", css)
        self.assertIn("createPersona", js)
        self.assertIn("archivePersona", js)
        self.assertIn("/personas", js)
        self.assertIn("session-group-label", js)
        self.assertIn("tone-${roleColor}", js)
        self.assertIn("streamSessionMessages", js)
        self.assertIn("/stream", js)
        self.assertIn("TextDecoder", js)
        self.assertIn("runAction", js)
        self.assertIn("setMessageSending", js)
        self.assertIn("发送中", js)
        self.assertIn("发送失败，已恢复输入", js)
        self.assertIn("请先开始一个讨论", js)


if __name__ == "__main__":
    unittest.main()
